# specify the location of the named.conf file
named.conf:
    path: '/var/named/chroot/etc/named.local-zones.conf'
    named-restart-cmd: 'service named restart'

# settings for automatically testing the configuration with named-checkconf
named-checkconf:
    enable: false
    path:   '/usr/sbin/named-checkconf'
