# define your default zone settings
# {{name}} is replaced by the actual zone name

example-slave:
    type: slave
    masters: '{192.168.63.1;192.168.63.2;}'
    allow-query: '{ any; }'
    file: '"{{name}}.db"'
    
example-master:
    type: master
    masters: '{192.168.63.3;192.168.63.4;}'
    allow-query: '{ any; }'
    file: '"{{name}}.db"'